(() => {
  'use strict';
  const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
  const images = { G1:'assets/tiles/giraffe-kopf.jpg',G2:'assets/tiles/giraffe-hals.jpg',G3:'assets/tiles/giraffe-beine.jpg',F1:'assets/tiles/flamingo-kopf.jpg',F2:'assets/tiles/flamingo-koerper.jpg',F3:'assets/tiles/flamingo-beine.jpg',K1:'assets/tiles/koala-kopf.jpg',K2:'assets/tiles/koala-baum.jpg' };
  const names = { G1:'Giraffe – Kopf',G2:'Giraffe – Hals',G3:'Giraffe – Beine',F1:'Flamingo – Kopf',F2:'Flamingo – Körper',F3:'Flamingo – Beine',K1:'Koala – Kopf',K2:'Koala – Baum','.' :'Freies Feld' };
  const photo = ['G1','F3','F1','G2','K1','F2','G3','K2','.'];
  let state=photo.slice(), history=[], solution=[], solutionIndex=0, selected='G1', suggested=null, timer=null, seconds=0, cropper=null, cut=[], assignments=[], customImages={};
  const copy=a=>a.slice();
  function notice(id,message,type='info'){const e=$(id);if(e){e.textContent=message;e.className=`notice ${type}`}}
  function src(tile){return customImages[tile]||images[tile]||''}
  function name(tile){return names[tile]||tile}
  function renderTile(tile,index,click,opts={}){const b=document.createElement('button');b.type='button';b.className=`tile ${tile==='.'?'empty':''}`;b.dataset.tile=tile;if(tile==='.')b.textContent='FREI';else{const img=document.createElement('img');img.src=src(tile);img.alt=name(tile);img.onerror=()=>{img.remove();b.append(tile)};b.append(img);const badge=document.createElement('span');badge.className='tile-code';badge.textContent=tile;b.append(badge)}if(opts.movable)b.classList.add('movable');if(opts.suggested)b.classList.add('suggested');if(click)b.onclick=()=>click(index,tile);return b}
  function renderBoard(id,board,click,showMoves=false){const host=$(id);if(!host)return;host.innerHTML='';board.forEach((tile,index)=>{const movable=showMoves&&Engine.next(board).some(move=>move.state[index]==='.');host.append(renderTile(tile,index,click,{movable,suggested:tile===suggested}))})}
  function code(){const e=$('#code');if(e)e.value=state.join(',')}
  function stats(){text('#moves',history.length);const par=Number($('#par')?.textContent||0);text('#delta',Number.isFinite(par)?history.length-par:'–')}
  function text(id,value){const e=$(id);if(e)e.textContent=String(value)}
  function format(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
  function stopTimer(){if(timer)clearInterval(timer);timer=null}
  function startTimer(){stopTimer();seconds=0;text('#time','00:00');timer=setInterval(()=>{seconds++;text('#time',format(seconds))},1000)}
  function renderAll(){renderBoard('#game',state,move,true);renderBoard('#solveBoard',solutionIndex?solution[solutionIndex-1].state:state);code()}
  function move(index){const m=Engine.next(state).find(x=>x.state[index]==='.');if(!m){notice('#notice','Diese Kachel kann nicht bewegt werden.','warn');return}history.push(copy(state));state=copy(m.state);suggested=null;stats();renderAll();if(Engine.isGoal(state)){stopTimer();notice('#notice',`🎉 Geschafft! ${history.length} Züge in ${format(seconds)}.`, 'ok')}}
  function check(){if(!Engine.valid(state))return{ok:false,msg:'Ungültig: Alle acht Kacheln und genau ein freies Feld werden benötigt.'};if(!Engine.possible(state))return{ok:false,msg:'Gültig, aber unlösbar: Diese Schiebe-Parität erreicht keine der 12 Zielvarianten.'};const r=Engine.solve(state);return{ok:true,result:r,msg:`Gültig und lösbar: ${r.path.length} minimale Züge.`}}
  function random(){const [min,max]=($('#level').value||'7,12').split(',').map(Number);state=Engine.random(min,max);history=[];suggested=null;const r=Engine.solve(state);text('#par',r.path.length);stats();startTimer();notice('#notice',`Neue Variante: optimal ${r.path.length} Züge.`, 'info');renderAll();renderEditor()}
  function hint(){const c=check();if(!c.ok){notice('#notice',c.msg,'warn');return}const m=c.result.path[0];if(!m){notice('#notice','Das Puzzle ist schon gelöst.','ok');return}suggested=m.tile;notice('#notice',`💡 Tipp: ${name(m.tile)} ${m.word}.`,'warn');renderBoard('#game',state,move,true)}
  function solve(){const c=check();const list=$('#steps');list.innerHTML='';solution=[];solutionIndex=0;if(!c.ok){notice('#solveStatus',c.msg,'bad');renderAll();return}let current=copy(state);solution=c.result.path.map(m=>{current=copy(m.state);return{...m,state:copy(current)}});notice('#solveStatus',`${c.result.status} – ${solution.length} minimale Züge zu einem von 12 gültigen Zielen.`,'ok');solution.forEach((m,i)=>{const li=document.createElement('li');li.textContent=`${i+1}. ${name(m.tile)} ${m.arrow} ${m.word}`;li.onclick=()=>{solutionIndex=i+1;renderAll();[...list.children].forEach((x,n)=>x.classList.toggle('active',n===i))};list.append(li)});renderAll()}
  function renderPalette(){const p=$('#palette');p.innerHTML='';[...Engine.tiles].forEach((tile,i)=>{const b=renderTile(tile,i,null);b.className=`tile ${tile==='.'?'empty':''} ${tile===selected?'selected':''}`;b.onclick=()=>{selected=tile;renderPalette()};p.append(b)})}
  function renderEditor(){renderBoard('#edit',state,index=>{const old=state.indexOf(selected);if(old>=0)[state[index],state[old]]=[state[old],state[index]];else state[index]=selected;history=[];stats();renderAll();renderEditor()},false);const c=check();notice('#valid',c.msg,c.ok?'ok':'warn')}
  function loadCode(){const a=($('#codeLoad').value||'').split(',').map(x=>x.trim());if(!Engine.valid(a)){notice('#valid','Ungültiger Code.','bad');return}state=copy(a);history=[];stats();renderAll();renderEditor()}
  function refreshSaved(){const s=$('#saved');if(!window.Store?.all)return;s.innerHTML='';Store.all().forEach(v=>{const o=document.createElement('option');o.value=v.name;o.textContent=v.name;s.append(o)})}
  function loadImage(file){const r=new FileReader();r.onload=()=>{const img=$('#sourceImage');img.onload=()=>{ $('#cropWorkspace').classList.remove('hidden');cropper=ImageImport.createImageCropper({stage:$('#cropStage'),image:img,overlay:$('#cropOverlay'),details:$('#cropDetails')});cropper.reset()};img.src=r.result};r.readAsDataURL(file)}
  function cutTiles(){if(!cropper)return;cut=cropper.cutIntoNine(240);assignments=['G1','F3','F1','G2','K1','F2','G3','K2','.'];renderCuts();$('#importResults').classList.remove('hidden')}
  function assignmentOk(){return assignments.length===9&&Engine.tiles.every(t=>assignments.filter(x=>x===t).length===1)}
  function renderCuts(){const host=$('#cutPreview');host.innerHTML='';cut.forEach((data,i)=>{const card=document.createElement('div');card.className='cut-card';const img=document.createElement('img');img.src=data;const select=document.createElement('select');Engine.tiles.forEach(t=>{const o=document.createElement('option');o.value=t;o.textContent=t==='.'?'Frei':`${t} – ${name(t)}`;o.selected=assignments[i]===t;select.append(o)});select.onchange=()=>{assignments[i]=select.value;updateImport()};card.append(img,select);host.append(card)});updateImport()}
  function updateImport(){const ok=assignmentOk();$('#applyImported').disabled=!ok;$('#playImported').disabled=!ok;notice('#importStatus',ok?'Zuordnung vollständig. Du kannst das Puzzle übernehmen.':'Jede Rolle G1–K2 und Frei muss genau einmal gewählt werden.',ok?'ok':'warn')}
  function applyImport(play=false){if(!assignmentOk())return;customImages={};assignments.forEach((role,i)=>{if(role!=='.')customImages[role]=cut[i]});state=copy(assignments);history=[];suggested=null;const r=Engine.solve(state);text('#par',r.path.length);stats();renderAll();renderPalette();renderEditor();notice('#notice','Importiertes Puzzle übernommen.','ok');if(play)switchPage('play')}
  function switchPage(id){$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.page===id))}
  function bind(){ $$('.tab').forEach(b=>b.onclick=()=>switchPage(b.dataset.page));$('#random').onclick=random;$('#undo').onclick=()=>{if(history.length){state=history.pop();stats();renderAll();renderEditor()}};$('#hint').onclick=hint;$('#toSolver').onclick=()=>{switchPage('solver');solve()};$('#solve').onclick=solve;$('#first').onclick=()=>{solutionIndex=0;renderAll()};$('#back').onclick=()=>{solutionIndex=Math.max(0,solutionIndex-1);renderAll()};$('#next').onclick=()=>{solutionIndex=Math.min(solution.length,solutionIndex+1);renderAll()};$('#photoStart').onclick=()=>{state=copy(photo);history=[];stats();renderAll();renderEditor()};$('#clear').onclick=()=>{state=Array(9).fill('');renderAll();renderEditor()};$('#playEdited').onclick=()=>switchPage('play');$('#load').onclick=loadCode;$('#copy').onclick=()=>navigator.clipboard?.writeText(state.join(','));$('#save').onclick=()=>{if(Engine.valid(state)&&window.Store?.put){Store.put($('#saveName').value||'Variante',copy(state));refreshSaved()}};$('#loadSaved').onclick=()=>{const e=Store?.all?.().find(x=>x.name===$('#saved').value);if(e){state=copy(e.state||e.board);history=[];renderAll();renderEditor()}};$('#delete').onclick=()=>{if(confirm('Variante löschen?')){Store.del($('#saved').value);refreshSaved()}};$('#imageInput').onchange=e=>e.target.files[0]&&loadImage(e.target.files[0]);$('#cameraInput').onchange=e=>e.target.files[0]&&loadImage(e.target.files[0]);$('#resetCrop').onclick=()=>cropper?.reset();$('#cutTiles').onclick=cutTiles;$('#applyImported').onclick=()=>applyImport(false);$('#playImported').onclick=()=>applyImport(true)}
  document.addEventListener('DOMContentLoaded',()=>{bind();renderPalette();renderAll();renderEditor();refreshSaved();const r=Engine.solve(state);text('#par',r.path.length);stats();notice('#notice','Klicke eine orange markierte Kachel an. Ziel: Tiere korrekt senkrecht zusammensetzen; die Tier-Spalten dürfen vertauscht sein.','info');if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{})});
})();
