(() => {
  'use strict';
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  const images={A1:'assets/tiles/giraffe-kopf.jpg',A2:'assets/tiles/giraffe-hals.jpg',A3:'assets/tiles/giraffe-beine.jpg',B1:'assets/tiles/flamingo-kopf.jpg',B2:'assets/tiles/flamingo-koerper.jpg',B3:'assets/tiles/flamingo-beine.jpg',C1:'assets/tiles/koala-kopf.jpg',C2:'assets/tiles/koala-baum.jpg'};
  const names={A1:'A1',A2:'A2',A3:'A3',B1:'B1',B2:'B2',B3:'B3',C1:'C1',C2:'C2','.':'Frei'};
  const solvedRoles=['A1','B1','C1','A2','B2','C2','A3','B3','.'];
  const photo=['A1','B3','B1','A2','C1','B2','A3','C2','.'];
  let state=photo.slice(),history=[],solution=[],solutionIndex=0,selected='A1',suggested=null,timer=null,seconds=0,cropper=null,cut=[],tileRoles=[],customImages={},importMode='roles',sortSelection=null,sortSlots=[];
  let randomWorker=null,generating=false,generationId=0;
  const copy=a=>a.slice();
  function notice(id,msg,type='info'){const e=$(id);if(e){e.textContent=msg;e.className=`notice ${type}`}}
  function src(t){return customImages[t]||images[t]||''}function name(t){return names[t]||t}
  function tile(t,i,click,opt={}){const b=document.createElement('button');b.type='button';b.className=`tile ${t==='.'?'empty':''}`;if(t==='.')b.textContent='FREI';else{const im=document.createElement('img');im.src=src(t);im.alt=name(t);im.onerror=()=>{im.remove();b.append(t)};b.append(im);const badge=document.createElement('span');badge.className='tile-code';badge.textContent=t;b.append(badge)}if(opt.movable)b.classList.add('movable');if(opt.suggested)b.classList.add('suggested');if(click)b.onclick=()=>click(i,t);return b}
  function board(id,b,click,moves=false){const host=$(id);if(!host)return;host.innerHTML='';b.forEach((t,i)=>{const movable=moves&&Engine.next(b).some(m=>m.state[i]==='.');host.append(tile(t,i,click,{movable,suggested:t===suggested}))})}
  function text(id,v){const e=$(id);if(e)e.textContent=String(v)}function stats(){text('#moves',history.length);const p=Number($('#par')?.textContent||0);text('#delta',Number.isFinite(p)?history.length-p:'–')}
  function displayCode(){return state.map(t=>t==='.'?'Frei':t).join(',')}
  function parseCode(value){return value.split(',').map(x=>x.trim()==='Frei'?'.':x.trim())}
  function render(){board('#game',state,move,true);board('#solveBoard',solutionIndex?solution[solutionIndex-1].state:state);const e=$('#code');if(e)e.value=displayCode()}
  function move(i){const m=Engine.next(state).find(x=>x.state[i]==='.');if(!m)return;history.push(copy(state));state=copy(m.state);suggested=null;stats();render();if(Engine.isGoal(state)){clearInterval(timer);showSuccessModal()}}
  function showSuccessModal(){$('#modalMoves').textContent=history.length;$('#modalPar').textContent=$('#par').textContent;$('#modalTime').textContent=$('#time').textContent;$('#successModal').classList.remove('hidden')}
  function check(){if(!Engine.valid(state))return{ok:false,msg:'Ungültig: Alle acht Rasterteile und ein freies Feld werden benötigt.'};if(!Engine.possible(state))return{ok:false,msg:'Gültig, aber nach der gewählten Zielregel unlösbar.'};const r=Engine.solve(state);return{ok:true,result:r,msg:`Gültig und lösbar: ${r.path.length} minimale Züge.`}}
  function generateAsync(min,max,rule){return new Promise((resolve,reject)=>{try{if(typeof Worker==='undefined')throw Error('Web Worker nicht verfügbar');const worker=randomWorker||(randomWorker=new Worker('random-worker.js'));const id=++generationId;worker.onmessage=({data})=>{if(data.id!==id)return;if(data.type==='progress'){notice('#notice',`Neues Rätsel wird erstellt … ${data.count} Zustände vorbereitet.`,'info');return}worker.onmessage=null;worker.onerror=null;if(data.type==='result')resolve(data);else reject(Error(data.message||'Rätselgenerierung fehlgeschlagen.'))};worker.onerror=()=>{worker.terminate();randomWorker=null;reject(Error('Web Worker konnte nicht gestartet werden.'))};worker.postMessage({id,min,max,rule})}catch(error){reject(error)}})}
  async function randomPuzzle(){if(generating)return;generating=true;const button=$('#random'),level=$('#level'),goalRule=$('#goalRule'),label=button.textContent,rule=Engine.getRule(),oldState=Engine.key(state);const[min,max]=level.value.split(',').map(Number);button.disabled=level.disabled=goalRule.disabled=true;button.textContent='⏳ Wird erstellt …';notice('#notice','Neues Rätsel wird erstellt …','info');try{await new Promise(resolve=>requestAnimationFrame(()=>setTimeout(resolve,0)));let generated;try{generated=await generateAsync(min,max,rule)}catch(workerError){console.warn('Worker nicht verfügbar, lokale Generierung:',workerError);notice('#notice','Hintergrundberechnung nicht verfügbar – erstelle Rätsel lokal …','warn');await new Promise(resolve=>requestAnimationFrame(()=>setTimeout(resolve,0)));generated=Engine.random(min,max,true)}if(Engine.getRule()!==rule||Engine.key(state)!==oldState){notice('#notice','Rätselerstellung verworfen: Spielzustand wurde inzwischen geändert.','warn');return}state=generated.state;history=[];suggested=null;solution=[];solutionIndex=0;text('#par',generated.par);stats();seconds=0;clearInterval(timer);text('#time','00:00');timer=setInterval(()=>text('#time',`${String(Math.floor(++seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`),1000);render();editor({ok:true,msg:`Gültig und lösbar: ${generated.par} minimale Züge.`});notice('#notice',`Neue Variante: optimal ${generated.par} Züge.`,'ok')}catch(error){console.error(error);notice('#notice',error.message||'Rätsel konnte nicht erstellt werden.','bad')}finally{button.disabled=level.disabled=goalRule.disabled=false;button.textContent=label;generating=false}}
  function hint(){const c=check();if(!c.ok){notice('#notice',c.msg,'warn');return}const m=c.result.path[0];if(!m){notice('#notice','Das Puzzle ist bereits gelöst.','ok');return}suggested=m.tile;notice('#notice',`💡 Tipp: Feld ${name(m.tile)} ${m.word}.`,'warn');board('#game',state,move,true)}
  function solve(){const c=check(),list=$('#steps');list.innerHTML='';solution=[];solutionIndex=0;if(!c.ok){notice('#solveStatus',c.msg,'bad');return}let current=copy(state);solution=c.result.path.map(m=>{current=copy(m.state);return{...m,state:copy(current)}});notice('#solveStatus',`${solution.length} minimale Züge.`,'ok');solution.forEach((m,i)=>{const li=document.createElement('li');li.textContent=`${i+1}. Feld ${name(m.tile)} ${m.arrow} ${m.word}`;li.onclick=()=>{solutionIndex=i+1;render();[...list.children].forEach((x,n)=>x.classList.toggle('active',n===i))};list.append(li)});render()}
  function palette(){const p=$('#palette');p.innerHTML='';Engine.tiles.forEach((t,i)=>{const b=tile(t,i);b.classList.toggle('selected',t===selected);b.onclick=()=>{selected=t;palette()};p.append(b)})}
  function editor(knownStatus=null){board('#edit',state,i=>{const old=state.indexOf(selected);if(old>=0)[state[i],state[old]]=[state[old],state[i]];else state[i]=selected;history=[];stats();render();editor()});const c=knownStatus||check();notice('#valid',c.msg,c.ok?'ok':'warn')}
  function loadCode(){const a=parseCode($('#codeLoad').value);if(!Engine.valid(a)){notice('#valid','Ungültiger Rastercode.','bad');return}state=a;history=[];render();editor()}
  function useDefault(){customImages={};state=copy(photo);history=[];Engine.setRule('flexible');$('#goalRule').value='flexible';const r=Engine.solve(state);text('#par',r.path.length);stats();render();palette();editor();notice('#notice','Standard-Tierpuzzle wiederhergestellt.','ok');switchPage('play')}
  function loadImage(file){const r=new FileReader();r.onload=()=>{const im=$('#sourceImage');im.onload=()=>{$('#cropWorkspace').classList.remove('hidden');$('#importResults').classList.add('hidden');cropper=ImageImport.createImageCropper({stage:$('#cropStage'),image:im,overlay:$('#cropOverlay'),details:$('#cropDetails')});cropper.reset()};im.src=r.result};r.readAsDataURL(file)}
  function cuts(){if(!cropper)return;cut=cropper.cutIntoNine();tileRoles=solvedRoles.slice();importMode='roles';sortSelection=null;sortSlots=Array(9).fill(null);$('#roleMode').classList.add('active-mode');$('#sortMode').classList.remove('active-mode');$('#roleHelp').classList.remove('hidden');$('#sortHelp').classList.add('hidden');$('#cutPreview').classList.remove('hidden');$('#sortBoard').classList.add('hidden');renderCutPreview();$('#importResults').classList.remove('hidden');importStatus()}
  function roleOptions(role){return Engine.tiles.map(t=>`<option value="${t}" ${role===t?'selected':''}>${name(t)}</option>`).join('')}
  function renderCutPreview(){const h=$('#cutPreview');h.innerHTML='';cut.forEach((d,i)=>{const card=document.createElement('div');card.className='cut-card';const im=document.createElement('img');im.src=d;const sel=document.createElement('select');sel.innerHTML=roleOptions(tileRoles[i]);sel.onchange=()=>{const next=sel.value,old=tileRoles[i],other=tileRoles.indexOf(next);if(other!==-1&&other!==i)tileRoles[other]=old;tileRoles[i]=next;renderCutPreview();importStatus()};card.append(im,sel);h.append(card)})}
  function setImportMode(mode){importMode=mode;const roles=mode==='roles';$('#roleMode').classList.toggle('active-mode',roles);$('#sortMode').classList.toggle('active-mode',!roles);$('#roleHelp').classList.toggle('hidden',!roles);$('#sortHelp').classList.toggle('hidden',roles);$('#cutPreview').classList.toggle('hidden',!roles);$('#sortBoard').classList.toggle('hidden',roles);if(!roles){sortSelection=null;sortSlots=Array(9).fill(null);renderSortBoard()}}
  function renderSortBoard(){const host=$('#sortBoard');host.innerHTML='';solvedRoles.forEach((role,slot)=>{const el=document.createElement('button');el.type='button';el.className='sort-slot'+(sortSlots[slot]!==null?' selected':'');const source=sortSlots[slot];if(source!==null){const im=document.createElement('img');im.src=cut[source];el.append(im)}else el.textContent='Kachel wählen';const label=document.createElement('span');label.className='slot-label';label.textContent=name(role);el.append(label);el.onclick=()=>{if(sortSelection===null){if(source!==null){sortSelection=source;sortSlots[slot]=null;renderSortBoard()}return}const existing=sortSlots[slot];sortSlots[slot]=sortSelection;sortSelection=existing;renderSortBoard();importStatus()};host.append(el)});const available=document.createElement('div');available.className='sort-available';cut.forEach((d,i)=>{if(!sortSlots.includes(i)){const b=document.createElement('button');b.type='button';b.className='sort-slot'+(sortSelection===i?' selected':'');const im=document.createElement('img');im.src=d;b.append(im);b.onclick=()=>{sortSelection=i;renderSortBoard()};available.append(b)}});host.append(available)}
  function importStatus(){const ok=importMode==='roles'?tileRoles.length===9&&Engine.tiles.every(t=>tileRoles.filter(x=>x===t).length===1):sortSlots.length===9&&sortSlots.every(x=>x!==null);$('#applyImported').disabled=!ok;$('#playImported').disabled=!ok;notice('#importStatus',ok?'Zuordnung vollständig.':'Jede Rasterrolle muss genau einmal vergeben werden.',ok?'ok':'warn')}
  function applyImport(play){if($('#applyImported').disabled)return;customImages={};let boardState;if(importMode==='roles'){tileRoles.forEach((r,i)=>{if(r!=='.')customImages[r]=cut[i]});boardState=copy(tileRoles)}else{boardState=solvedRoles.slice();sortSlots.forEach((source,slot)=>{const role=solvedRoles[slot];if(role!=='.')customImages[role]=cut[source]})}state=boardState;history=[];const r=Engine.solve(state);text('#par',r.path.length);stats();render();palette();editor();notice('#notice','Importiertes Puzzle übernommen.','ok');if(play)switchPage('play')}
  function switchPage(id){$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.page===id))}
  document.addEventListener('DOMContentLoaded',()=>{text('.site-footer span','Schiebepuzzle Studio · Version 1.8.0');$('#notice').setAttribute('role','status');$$('.tab').forEach(b=>b.onclick=()=>switchPage(b.dataset.page));$('#random').onclick=randomPuzzle;$('#undo').onclick=()=>{if(history.length){state=history.pop();stats();render();editor()}};$('#hint').onclick=hint;$('#toSolver').onclick=()=>{switchPage('solver');solve()};$('#solve').onclick=solve;$('#first').onclick=()=>{solutionIndex=0;render()};$('#back').onclick=()=>{solutionIndex=Math.max(0,solutionIndex-1);render()};$('#next').onclick=()=>{solutionIndex=Math.min(solution.length,solutionIndex+1);render()};$('#photoStart').onclick=()=>{state=copy(photo);history=[];render();editor()};$('#clear').onclick=()=>{state=Array(9).fill('');render();editor()};$('#playEdited').onclick=()=>switchPage('play');$('#load').onclick=loadCode;$('#copy').onclick=()=>navigator.clipboard?.writeText(displayCode());$('#imageInput').onchange=e=>e.target.files[0]&&loadImage(e.target.files[0]);$('#cameraInput').onchange=e=>e.target.files[0]&&loadImage(e.target.files[0]);$('#useDefault').onclick=useDefault;$('#goalRule').onchange=e=>{Engine.setRule(e.target.value);const r=Engine.solve(state);text('#par',r.path.length);stats();editor();notice('#notice',e.target.value==='strict'?'Strikte A1–C3-Zielregel aktiv.':'Flexible Spaltenreihenfolge aktiv.','info')};$('#resetCrop').onclick=()=>cropper?.reset();$('#cutTiles').onclick=cuts;$('#roleMode').onclick=()=>setImportMode('roles');$('#sortMode').onclick=()=>setImportMode('sort');$('#applyImported').onclick=()=>applyImport(false);$('#playImported').onclick=()=>applyImport(true);$('#modalNew').onclick=()=>{$('#successModal').classList.add('hidden');randomPuzzle()};$('#modalClose').onclick=()=>$('#successModal').classList.add('hidden');palette();render();editor();const r=Engine.solve(state);text('#par',r.path.length);stats();notice('#notice','Klicke eine orange markierte Kachel an. Ziel: Rasterteile korrekt zusammensetzen.','info');if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{})});
})();
