"use strict";
self.window=self;
importScripts("puzzle-engine.js");
const total=362880;
const fac=[1,1,2,6,24,120,720,5040,40320];
const symbols=Engine.tiles;
const cache=new Map();
function rank(state){const remaining=[0,1,2,3,4,5,6,7,8];let n=0;for(let i=0;i<9;i++){const j=remaining.indexOf(state[i]);n+=j*fac[8-i];remaining.splice(j,1)}return n}
function unrank(n){const remaining=[0,1,2,3,4,5,6,7,8],state=[];for(let i=0;i<9;i++){const f=fac[8-i],j=Math.floor(n/f);n%=f;state.push(remaining.splice(j,1)[0])}return state}
function getCache(rule){if(cache.has(rule))return cache.get(rule);const distances=new Uint8Array(total);distances.fill(255);const queue=[],buckets=Array.from({length:32},()=>[]);const goals=rule==='strict'?Engine.goals.filter(g=>g.join(',')==='A1,B1,C1,A2,B2,C2,A3,B3,.'):Engine.goals;if(!goals.length)throw Error('Keine gültige Zielanordnung.');for(const goal of goals){const code=rank(goal.map(t=>symbols.indexOf(t)));if(distances[code]!==255)continue;distances[code]=0;queue.push(code);buckets[0].push(code)}const data={distances,queue,buckets,head:0,last:-1};cache.set(rule,data);return data}
function prepare(data,max,id){const {distances,queue,buckets}=data;while(data.head<queue.length){const code=queue[data.head],depth=distances[code];if(depth>=max)break;data.head++;const state=unrank(code),empty=state.indexOf(8);for(const pos of Engine.neighbors[empty]){[state[empty],state[pos]]=[state[pos],state[empty]];const next=rank(state);[state[empty],state[pos]]=[state[pos],state[empty]];if(distances[next]!==255)continue;distances[next]=depth+1;queue.push(next);buckets[depth+1].push(next)}if((data.head&8191)===0)self.postMessage({id,type:'progress',count:data.head})}}
self.onmessage=({data})=>{const {id,rule,min,max}=data;try{if(!['strict','flexible'].includes(rule)||!Number.isInteger(min)||!Number.isInteger(max)||min<1||max>31||min>max)throw Error('Ungültiger Schwierigkeitsgrad.');const dataCache=getCache(rule);prepare(dataCache,max,id);const depths=[];for(let depth=min;depth<=max;depth++)if(dataCache.buckets[depth].length)depths.push(depth);if(!depths.length)throw Error('Für diese Schwierigkeit wurde kein Rätsel gefunden.');const depth=depths[Math.floor(Math.random()*depths.length)],bucket=dataCache.buckets[depth];let code=bucket[Math.floor(Math.random()*bucket.length)];if(bucket.length>1){for(let i=0;i<8&&code===dataCache.last;i++)code=bucket[Math.floor(Math.random()*bucket.length)]}dataCache.last=code;self.postMessage({id,type:'result',state:unrank(code).map(n=>symbols[n]),par:depth})}catch(error){self.postMessage({id,type:'error',message:error.message||String(error)})}};
